title: Bob Vo # your name (or website title) here
logo: "images/circle-cropped-profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I am currently a Graduate Machine Learning Student at Ryerson University. Topics of interest: Deep Learning, Computer Vision, Signal Processing.
  

  <br><br>
  <a href="https://www.linkedin.com/in/bob-vo/">View My LinkedIn Profile</a> 
  
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br> 
    <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br> 
    <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br> 
    <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br> 
    <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br> 
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
